const Images = {
  burger: require("../src/burger.png"),
  sunset: require("../src/sunset-.png"),
  sunrise: require("../src/sunrise.png"),
  chocolate: require("../src/chocolate.png"),
  coffee: require("../src/coffee-beans.png"),
  comedy: require("../src/comedy.png"),
  flight: require("../src/flight.png"),
  landscape: require("../src/landscape.png"),
  pizza: require("../src/pizza.png"),
  rain: require("../src/rain.png"),
  scream: require("../src/scream.png"),
  tea: require("../src/tea-bag.png"),
  train: require("../src/train.png"),
  vacation: require("../src/vacations.png"),
  vanilla: require("../src/ice-cream.png"),
  snow: require("../src/winter.png"),
  snail: require("../src/snail.png"),
  turtle: require("../src/turtle.png"),
  lion: require("../src/lion.png"),
  snake: require("../src/anaconda.png"),
  gift: require("../src/giftbox.png"),
  loveletter: require("../src/love-letter.png"),
  sightseeing: require("../src/sightseeing.png"),
};

export default Images;
